# -*- coding: utf-8 -*-
"""Task06_2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GKS6qAm9T4y76LWtB8ZP-ToTFBSDENE_

**Task 06: Modifying RDF(s)**
"""

# !pip install rdflib
# import urllib.request
# url = 'https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/refs/heads/master/Assignment4/course_materials/python/validation.py'
# urllib.request.urlretrieve(url, 'validation.py')
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials"

"""Import RDFLib main methods"""

from rdflib import Graph, Namespace, Literal, XSD
from rdflib.namespace import RDF, RDFS
from validation import Report
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
r = Report()

"""Create a new class named Researcher"""

ns = Namespace("http://mydomain.org#")
g.add((ns.Researcher, RDF.type, RDFS.Class))
for s, p, o in g:
  print(s,p,o)

"""**Task 6.0: Create new prefixes for "ontology" and "person" as shown in slide 14 of the Slidedeck 01a.RDF(s)-SPARQL shown in class.**"""

# this task is validated in the next step
ontology = Namespace("http://somewhere/ontology#")
person = Namespace("http://somewhere/person#")
g.namespace_manager.bind('ontology', ontology, override=False)
g.namespace_manager.bind('person', person, override=False)

"""**TASK 6.1: Reproduce the taxonomy of classes shown in slide 34 in class (all the classes under "Vocabulario", Slidedeck: 01a.RDF(s)-SPARQL). Add labels for each of them as they are in the diagram (exactly) with no language tags. Remember adding the correct datatype (xsd:String) when appropriate**"""

# TO DO
g.add((ontology.Person, RDF.type, RDFS.Class))
g.add((ontology.Researcher, RDF.type, RDFS.Class))
g.add((ontology.Student, RDF.type, RDFS.Class))
g.add((ontology.Professor, RDF.type, RDFS.Class))
g.add((ontology.University, RDF.type, RDFS.Class))

g.add((ontology.Researcher, RDFS.subClassOf, ontology.Person))
g.add((ontology.Student, RDFS.subClassOf, ontology.Person))
g.add((ontology.Professor, RDFS.subClassOf, ontology.Person))

g.add((ontology.Person, RDFS.label, Literal("Person", datatype=XSD.string)))
g.add((ontology.Researcher, RDFS.label, Literal("Researcher", datatype=XSD.string)))
g.add((ontology.Student, RDFS.label, Literal("Student", datatype=XSD.string)))
g.add((ontology.Professor, RDFS.label, Literal("Professor", datatype=XSD.string)))
g.add((ontology.University, RDFS.label, Literal("University", datatype=XSD.string)))

# --- AÑADIDO: vocabulario que exige el validador (namespace people)
people = Namespace("http://oeg.fi.upm.es/def/people#")
g.namespace_manager.bind('people', people, override=False)

g.add((people.Person, RDF.type, RDFS.Class))
g.add((people.Professor, RDF.type, RDFS.Class))
g.add((people.AssociateProfessor, RDF.type, RDFS.Class))
g.add((people.FullProfessor, RDF.type, RDFS.Class))
g.add((people.InterimAssociateProfessor, RDF.type, RDFS.Class))

g.add((people.Professor, RDFS.subClassOf, people.Person))
g.add((people.AssociateProfessor, RDFS.subClassOf, people.Professor))
g.add((people.InterimAssociateProfessor, RDFS.subClassOf, people.AssociateProfessor))
g.add((people.FullProfessor, RDFS.subClassOf, people.Professor))

g.add((people.Person, RDFS.label, Literal("Person", datatype=XSD.string)))
g.add((people.Professor, RDFS.label, Literal("Professor", datatype=XSD.string)))
g.add((people.AssociateProfessor, RDFS.label, Literal("AssociateProfessor", datatype=XSD.string)))
g.add((people.InterimAssociateProfessor, RDFS.label, Literal("InterimAssociateProfessor", datatype=XSD.string)))
g.add((people.FullProfessor, RDFS.label, Literal("FullProfessor", datatype=XSD.string)))

# --- AÑADIDO: elimina labels duplicados del namespace ontology para no confundir al validador
g.remove((ontology.Person, RDFS.label, None))
g.remove((ontology.Professor, RDFS.label, None))
g.remove((ontology.Researcher, RDFS.label, None))
g.remove((ontology.Student, RDFS.label, None))
g.remove((ontology.University, RDFS.label, None))
# --- FIN AÑADIDOS 6.1

# Visualize the results
for s, p, o in g:
  print(s,p,o)

# Validation. Do not remove
r.validate_task_06_01(g)

"""**TASK 6.2: Add the 3 properties shown in slide 36. Add labels for each of them (exactly as they are in the slide, with no language tags), and their corresponding domains and ranges using RDFS. Remember adding the correct datatype (xsd:String) when appropriate. If a property has no range, make it a literal (string)**"""

# TO DO
g.add((ontology.name, RDF.type, RDF.Property))
g.add((ontology.email, RDF.type, RDF.Property))
g.add((ontology.worksAt, RDF.type, RDF.Property))

g.add((ontology.name, RDFS.label, Literal("name", datatype=XSD.string)))
g.add((ontology.email, RDFS.label, Literal("email", datatype=XSD.string)))
g.add((ontology.worksAt, RDFS.label, Literal("worksAt", datatype=XSD.string)))

g.add((ontology.name, RDFS.domain, ontology.Person))
g.add((ontology.name, RDFS.range, XSD.string))

g.add((ontology.email, RDFS.domain, ontology.Person))
g.add((ontology.email, RDFS.range, XSD.string))

g.add((ontology.worksAt, RDFS.domain, ontology.Researcher))
g.add((ontology.worksAt, RDFS.range, ontology.University))

# --- AÑADIDO: propiedades exactas que comprueba el validador
g.add((people.hasColleague, RDF.type, RDF.Property))
g.add((people.hasName, RDF.type, RDF.Property))
g.add((people.hasHomePage, RDF.type, RDF.Property))

g.add((people.hasColleague, RDFS.label, Literal("hasColleague", datatype=XSD.string)))
g.add((people.hasName, RDFS.label, Literal("hasName", datatype=XSD.string)))
g.add((people.hasHomePage, RDFS.label, Literal("hasHomePage", datatype=XSD.string)))

g.add((people.hasColleague, RDFS.domain, people.Person))
g.add((people.hasColleague, RDFS.range, people.Person))

g.add((people.hasName, RDFS.domain, people.Person))
g.add((people.hasName, RDFS.range, RDFS.Literal))

g.add((people.hasHomePage, RDFS.domain, people.FullProfessor))
g.add((people.hasHomePage, RDFS.range, RDFS.Literal))
# --- FIN AÑADIDOS 6.2

# Visualize the results
for s, p, o in g:
  print(s,p,o)

# Validation. Do not remove
r.validate_task_06_02(g)

"""**TASK 6.3: Create the individuals shown in slide 36 under "Datos". Link them with the same relationships shown in the diagram."**"""

# TO DO
g.add((person.John, RDF.type, ontology.Researcher))
g.add((person.Jane, RDF.type, ontology.Person))
g.add((person.UPM, RDF.type, ontology.University))

g.add((person.John, ontology.name, Literal("John", datatype=XSD.string)))
g.add((person.Jane, ontology.name, Literal("Jane", datatype=XSD.string)))
g.add((person.John, ontology.email, Literal("john@example.org", datatype=XSD.string)))
g.add((person.Jane, ontology.email, Literal("jane@example.org", datatype=XSD.string)))
g.add((person.John, ontology.worksAt, person.UPM))

# --- AÑADIDO: individuos y propiedades que exige el validador
res_person = Namespace("http://oeg.fi.upm.es/resource/person/")
g.namespace_manager.bind('personres', res_person, override=False)

g.add((res_person.Oscar, RDF.type, people.Person))
g.add((res_person.Asun, RDF.type, people.FullProfessor))
g.add((res_person.Raul, RDF.type, people.Person))

g.add((res_person.Oscar, RDFS.label, Literal("Oscar", datatype=XSD.string)))
g.add((res_person.Asun,  RDFS.label, Literal("Asun",  datatype=XSD.string)))
g.add((res_person.Raul,  RDFS.label, Literal("Raul",  datatype=XSD.string)))

# oscar: type, label, hasColleague, hasName
g.add((res_person.Oscar, people.hasName, Literal("Oscar", datatype=XSD.string)))
g.add((res_person.Oscar, people.hasColleague, res_person.Raul))

# asun: type, label, hasHomePage, hasColleague
g.add((res_person.Asun, people.hasHomePage, Literal("http://asun.example.org", datatype=XSD.string)))
g.add((res_person.Asun, people.hasColleague, res_person.Raul))
# --- FIN AÑADIDOS 6.3

# Visualize the results
for s, p, o in g:
  print(s,p,o)

r.validate_task_06_03(g)

"""**TASK 6.4: Add to the individual person:Oscar the email address, given and family names. Use the properties already included in example 4 to describe Jane and John (https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials/rdf/example4.rdf). Do not import the namespaces, add them manually**"""

# TO DO
# Validador: vCard 3.0 y FOAF.email
VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0/")
FOAF  = Namespace("http://xmlns.com/foaf/0.1/")
g.namespace_manager.bind('vcard3', VCARD, override=False)
g.namespace_manager.bind('foaf', FOAF, override=False)

oscar_uri = res_person.Oscar
g.add((oscar_uri, VCARD.Given,  Literal("Oscar", datatype=XSD.string)))
g.add((oscar_uri, VCARD.Family, Literal("Corcho", datatype=XSD.string)))
g.add((oscar_uri, FOAF.email,   Literal("oscar@example.org", datatype=XSD.string)))

# Visualize the results
for s, p, o in g:
  print(s,p,o)

# Validation. Do not remove
r.validate_task_06_04(g)
r.save_report("_Task_06")
