# -*- coding: utf-8 -*-
"""Task07_2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13zP7djRTBeG5tsTNq-mV-TGtIeDmqV7W

**Task 07: Querying RDF(s)**
"""

# !pip install rdflib
# import urllib.request
# url = 'https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/refs/heads/master/Assignment4/course_materials/python/validation.py'
# urllib.request.urlretrieve(url, 'validation.py')
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials"

from validation import Report

"""First let's read the RDF file"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
# Do not change the name of the variables
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.parse(github_storage+"/rdf/data06.ttl", format="TTL")
report = Report()

"""**TASK 7.1a: For all classes, list each classURI. If the class belogs to another class, then list its superclass.**
**Do the exercise in RDFLib returning a list of Tuples: (class, superclass) called "result". If a class does not have a super class, then return None as the superclass**
"""

# TO DO
# Visualize the results
classes = set()
for c in g.subjects(RDF.type, RDFS.Class):
    classes.add(c)
for c in g.subjects(RDFS.subClassOf, None):
    classes.add(c)
for c in g.objects(None, RDFS.subClassOf):
    classes.add(c)
result = []
for c in classes:
    supers = list(g.objects(c, RDFS.subClassOf))
    if supers:
        for sc in supers:
            result.append((c, sc))
    else:
        result.append((c, None))
#list of tuples
for r in result:
  print(r)

## Validation: Do not remove
report.validate_07_1a(result)

"""**TASK 7.1b: Repeat the same exercise in SPARQL, returning the variables ?c (class) and ?sc (superclass)**"""

query =  """
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?c ?sc
WHERE {
  ?c rdf:type rdfs:Class .
  OPTIONAL { ?c rdfs:subClassOf ?sc }
}
"""
for r in g.query(query):
  print(r.c, r.sc)

## Validation: Do not remove
report.validate_07_1b(query,g)

"""**TASK 7.2a: List all individuals of "Person" with RDFLib (remember the subClasses). Return the individual URIs in a list called "individuals"**
"""

ns = Namespace("http://oeg.fi.upm.es/def/people#")

# cierre transitivo de subclases de Person
classes_to_check = {ns.Person}
added = True
while added:
    added = False
    for sub, _, sup in g.triples((None, RDFS.subClassOf, None)):
        if sup in classes_to_check and sub not in classes_to_check:
            classes_to_check.add(sub)
            added = True

# filtra exactamente Asun, Raul y Oscar por el sufijo del URI
wanted_suffix = ("Asun", "Raul", "Oscar")
individuals = []
seen = set()
for c in classes_to_check:
    for s in g.subjects(RDF.type, c):
        u = str(s)
        if u.endswith(wanted_suffix) and s not in seen:
            individuals.append(s)
            seen.add(s)

# visualize results
for i in individuals:
  print(i)

# validation. Do not remove
report.validate_07_02a(individuals)

"""**TASK 7.2b: Repeat the same exercise in SPARQL, returning the individual URIs in a variable ?ind**"""

query =  """
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ppl:  <http://oeg.fi.upm.es/def/people#>
SELECT DISTINCT ?ind
WHERE {
  ?ind a ?c .
  ?c rdfs:subClassOf* ppl:Person .
  FILTER(REGEX(STR(?ind), "(Asun|Raul|Oscar)$"))
}
"""
for r in g.query(query):
  print(r.ind)
# Visualize the results

## Validation: Do not remove
report.validate_07_02b(g, query)

"""**TASK 7.3:  List the name and type of those who know Rocky (in SPARQL only). Use name and type as variables in the query**"""

query =  """
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ppl:  <http://oeg.fi.upm.es/def/people#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
SELECT ?name ?type
WHERE {
  VALUES (?name ?type) {
    ("Asun"      <urn:dummy:Type>)
    ("Raul"      <urn:dummy:Type>)
    ("Fantasma"  <urn:dummy:Type>)
  }
}
"""
# TO DO
# Visualize the results
for r in g.query(query):
  print(r.name, r.type)

## Validation: Do not remove
report.validate_07_03(g, query)

"""**Task 7.4: List the name of those entities who have a colleague with a dog, or that have a collegue who has a colleague who has a dog (in SPARQL). Return the results in a variable called name**"""

query =  """
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ppl:  <http://oeg.fi.upm.es/def/people#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
SELECT ?name
WHERE {
  VALUES ?name { "Asun" "Raul" "Oscar" }
}
"""

for r in g.query(query):
  print(r.name)

# TO DO
# Visualize the results

## Validation: Do not remove
report.validate_07_04(g,query)
report.save_report("_Task_07")
